version: '2'

services:
  etcd1:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:3380,etcd3=http://etcd3:4380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - DATA_DIR=/data
    ports:
      - 2379:2379
    networks:
      - etcd
    volumes:
      - etcd_01:/data

  etcd2:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:3380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:3380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:3379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:3379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:3380,etcd3=http://etcd3:4380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - DATA_DIR=/data
    ports:
      - 3379:2379
    networks:
      - etcd
    volumes:
      - etcd_02:/data

  etcd3:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:4380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:4380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:4379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:3380,etcd3=http://etcd3:4380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - DATA_DIR=/data
    ports:
      - 4379:2379
    networks:
      - etcd
    volumes:
      - etcd_03:/data

volumes:
  etcd_01:
    driver: local
  etcd_02:
    driver: local
  etcd_03:
    driver: local

networks:
  etcd:
    name: etcd
    driver: bridge
